project:
  type: website

website:
  title: "4ST621"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Course_Intro.qmd
  sidebar:
     contents:
     - Course_Intro.qmd
     - section: "Probability Theory"
       contents:
        - LN1.qmd
        - LN2.qmd
        - LN3.qmd
        - LN4.qmd
        - LN5.qmd
        - LN6.qmd
        - LN7.qmd
        - LN8.qmd
     - section: "Mathematical Statistics"
       contents:
        - LN9.qmd
        - LN10.qmd
        - LN11.qmd
        - LN12.qmd
        - LN13.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual