---
title: "Hypothesis testing - introduction"
author: "Adam Cabla"
---

## Introduction

In this chapter, we are getting into the core of the inferential part of this course - statistical hypothesis testing. In the rough distinction, we can assume there are three core tasks of statistics as a whole: description (exploration), prediction and inference. So let´s ask the core question: Is it enough to describe data? Do the data speak for themselves?

As the first question go, it can be enough to describe the data, depending on the step of the whole process we are in. As for the second question, my answer is loud NO. Data never speak for themselves. Even in exploratory research, decisions have to be made on what and how to explore and present. Especially in multivariate setting, there is a bunch of possibilities to go with.

But let now turn to the inference: our question is not focused on how data look like, but how they came into existence; what is their generating process? What is generalisible and under which assumptions?

Statistical hypothesis testing ought to be tightly connected either to the scientific process or to the decision-making process.

### Epistemology

Espistemology is a branch of philosophy, that deals with the important topic: how do we, humans, acquire knowledge and how should we acquire knowledge. It has a long history filled with many famous names, from ancient Greeks through philosophers like Descartes, Hume, Kant, or Mill, but we will just briefly introduce the one, that shook the field in the first half of the 20th century - Karl Popper and his followers known as critical rationalists.

What was so revolutionary about the Karl Popper? His idea of falsificationism. Up until this point, knowledge was considered to be justified true belief, and the means of this justification were the most debated issue - whether we can justify a belief via reasoning (rationalism) or via observing (empiricism). Science used to be considered as something built *via positiva* - by adding; accumulating knowledge in, usually small, steps.

But the idea here was, that science should be built *via negativa* - by substracting; trying to falsify what we believe. In the end, knowledge ought to be a collection of ideas, that survived rigorous testing, were put in ***mortal danger**.*

As a side note, there is humorous caricature reference to this in the work of famous Czech (imaginary) genius Jara da Cimrman - at the beginning, there is an error, but totally precise; in the process we are falsifying this error and at the end we completely falsified the error and we know nothing.

### Statistical Inference as a Part of Scientific Process

### Causality

### General Frequentist Approach

#### Lady Lasting Tea

### The Two Origins of the NHST

#### Fisher´s Significance Testing

#### Neyman-Pearson´s Hypothesis Testing

### Null Hypothesis Significance Testing  
